@echo off
echo Starting FastAPI Backend...
start /b cmd /c ".\venv\Scripts\activate && python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"

echo Starting Streamlit Frontend...
start /b cmd /c ".\venv\Scripts\activate && streamlit run frontend\app.py --server.port 8501 --server.headless true"
